/* recognizeExp.c, Gerard Renardel, 29 January 2014
 *
 * In this file a recognizer acceptExpression is definined that can recognize
 * arithmetical expressions generated by the following BNF grammar:
 *
 * <expression>  ::= <term> { '+'  <term> | '-' <term> }
 *
 * <term>       ::= <factor> { '*' <factor> | '/' <factor> }
 *
 * <factor>     ::= <number> | <identifier> | '(' <expression> ')'
 *
 * Input for the recognizer is the token list constructed by the scanner (in scanner.c).
 * For the recognition of a token list the method of *recursive descent* is used.
 * It relies on the use of three functions for the recognition and processing of
 * terms, factors and expressions, respectively.
 * These three functions are defined with mutual recursion, corresponding with the
 * structure of the BNF grammar.
 */

#include <stdio.h>  /* getchar, printf */
#include <stdlib.h> /* NULL */
#include <string.h>
#include "scanner.h"
#include "recognizeEquation.h"


/* The functions acceptNumber, acceptIdentifier and acceptCharacter have as
 * (first) argument a pointer to an token list; moreover acceptCharacter has as
 * second argument a character. They check whether the first token
 * in the list is a number, an identifier or the given character, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int acceptNumber(List *lp) {
  if (*lp != NULL && (*lp)->tt == Number) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptIdentifier(List *lp, int *var, char *s) {
  if (*lp != NULL && (*lp)->tt == Identifier ) {
        if(*var==0){
            strcpy(s, ((*lp)->t).identifier);
            *var+=1;
        }
        if(strcmp(s, ((*lp)->t).identifier)){
            *var+=1;
        }
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptCharacter(List *lp, char c) {
  if (*lp != NULL && (*lp)->tt == Symbol && ((*lp)->t).symbol == c ) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

/* The functions acceptFactor, acceptTerm and acceptExpression have as
 * argument a pointer to a token list. They check whether the token list
 * has an initial segment that can be recognized as factor, term or expression, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int countDeg(List *lp, int *deg){
  if(*lp!=NULL&&(*lp)->tt==Number){
    if(((*lp)->t).number>*deg){
		*deg=((*lp)->t).number;
    }
    *lp=(*lp)->next;
	return 1;
  } else {
	return 0;
    }
}

int acceptTerm(List *lp, int *deg, int *var, char *s) {
	if(acceptNumber(lp)){
		if(acceptIdentifier(lp, var, s)){
			if(acceptCharacter(lp, '^')){
				return countDeg(lp, deg);
			}
            return 1;
		}
		return 1;
	}
	if(acceptIdentifier(lp, var, s)){
		if(acceptCharacter(lp, '^')){
			return countDeg(lp, deg);
		}
		return 1;
	}

	return 0;
}


int acceptExpression(List *lp, int *deg, int *var, char *s) {
  if(acceptCharacter(lp, '-'));
  if ( !acceptTerm(lp, deg, var, s) ) {
    return 0;
  }
  while ( acceptCharacter(lp,'+') || acceptCharacter(lp,'-') ) {
    if ( !acceptTerm(lp, deg, var, s) ) {
      return 0;
    }
  } /* no + or -, so we reached the end of the expression */
  return 1;
}

int acceptEquation(List *lp, int *deg, int *var, char *s){
	return acceptExpression(lp, deg, var, s) &&
	acceptCharacter(lp, '=') &&
	acceptExpression(lp, deg, var, s);
}


void recognizeEquation() {
  char *ar;
  int deg=-1, var=0, sLen;
  List tl, tl1;
  printf("give an equation: ");
  ar = readInput(&sLen);
  while (ar[0] != '!') {
    char *s = malloc((sLen+1)*sizeof(char));
    tl = tokenList(ar);
    printList(tl);
    tl1 = tl;
    if ( acceptEquation(&tl1, &deg, &var, s) && tl1 == NULL ) {
      printf("this is an equation");
      if(var==1&&deg==-1){
        deg=1;
      }
      if(var==1){
            printf(" in 1 variable of degree %d\n", deg);
      } else {
        printf(", but not in 1 variable\n");
      }
    } else {
      printf("this is not an equation\n");
    }
    free(ar);
    freeTokenList(tl);
    deg=-1;
    var=0;
    printf("\ngive an equation: ");
    ar = readInput(&sLen);
  }
  free(ar);
  printf("good bye\n");
}


