/* recognizeExp.c, Gerard Renardel, 29 January 2014
 *
 * In this file a recognizer acceptExpression is definined that can recognize
 * arithmetical expressions generated by the following BNF grammar:
 *
 * <expression>  ::= <term> { '+'  <term> | '-' <term> }
 *
 * <term>       ::= <factor> { '*' <factor> | '/' <factor> }
 *
 * <factor>     ::= <number> | <identifier> | '(' <expression> ')'
 *
 * Input for the recognizer is the token list constructed by the scanner (in scanner.c).
 * For the recognition of a token list the method of *recursive descent* is used.
 * It relies on the use of three functions for the recognition and processing of
 * terms, factors and expressions, respectively.
 * These three functions are defined with mutual recursion, corresponding with the
 * structure of the BNF grammar.
 */

#include <stdio.h>  /* getchar, printf */
#include <stdlib.h> /* NULL */
#include <string.h>
#include "scanner.h"
#include "recognizeEquation.h"


/* The functions acceptNumber, acceptIdentifier and acceptCharacter have as
 * (first) argument a pointer to an token list; moreover acceptCharacter has as
 * second argument a character. They check whether the first token
 * in the list is a number, an identifier or the given character, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int acceptNumber(List *lp) {
  if (*lp != NULL && (*lp)->tt == Number) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptIdentifier(List *lp) {
  if (*lp != NULL && (*lp)->tt == Identifier ) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptCharacter(List *lp, char c) {
  if (*lp != NULL && (*lp)->tt == Symbol && ((*lp)->t).symbol == c ) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

/* The functions acceptFactor, acceptTerm and acceptExpression have as
 * argument a pointer to a token list. They check whether the token list
 * has an initial segment that can be recognized as factor, term or expression, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int countDeg(List *lp, int *deg){
  if((*lp)->tt!=Number){
	return 0;
  } else {
	if(((*lp)->t).number>*deg){
		*deg=((*lp)->t).number;
		*lp=(*lp)->next;
		}
	}
  return 1;
}

int acceptTerm(List *lp, int *deg) {
	if(acceptNumber(lp)){
		if(acceptIdentifier(lp)){
			if(acceptCharacter(lp, '^')){
				return countDeg(lp, deg);
			}
		}
		return 1;
	}
	if(acceptIdentifier(lp)){
		if(acceptCharacter(lp, '^')){
			return countDeg(lp, deg);
		}
	}
	
	return 0;
}


int acceptExpression(List *lp, int *deg) {
  if(acceptCharacter(lp, '-'));
  if ( !acceptTerm(lp, deg) ) {
    return 0;
  }
  while ( acceptCharacter(lp,'+') || acceptCharacter(lp,'-') ) {
    if ( !acceptTerm(lp, deg) ) {
      return 0;
    }
  } /* no + or -, so we reached the end of the expression */
  return 1;
}

int acceptEquation(List *lp, int *deg){
	return acceptExpression(lp, deg) &&
	acceptCharacter(lp, '=') &&
	acceptExpression(lp, deg);
}

/* The next function can be used to demonstrate the recognizer.
 */
/* 
void varDeg(List *lp){
	int countDeg=0, countVar=0;
	int n;
	int tempCount;
	int arDeg[20];
	char stVar[40] = {'0'};
	while(*lp!=NULL){
		if((*lp)->tt==Symbol&&((*lp)->t).symbol=='^'){
			*lp=(*lp)->next;
			n = ((*lp)->t).number;
			//printf("%d\n", n);
			if(n>0){
				arDeg[countDeg]=n;
				countDeg++;
			}
		}
		
		if((*lp)->tt==Identifier){
			if(countVar!=2){
				if(stVar[0]=='0'){
					strcpy(stVar, ((*lp)->t).identifier);
					countVar++;
				} else {
					if (strcmp(stVar, ((*lp)->t).identifier)){
						countVar++;
					}
				}
			}
		}		
		*lp=(*lp)->next;
	}
	
	tempCount=countDeg;
	for(int i=0; i<countDeg; i++){
		for(int j=i+1;j<countDeg; j++){
			if(arDeg[i]==arDeg[j]){
				tempCount--;
			}
		}
	}
	if(countVar==1){
		countDeg++;
		printf(" in 1 variable of degree %d\n", countDeg);
	}else{
		printf(", but not in 1 variable\n");
	}
	
}
*/ 
	
void recognizeEquation() {
  char *ar;
  int deg=0;
  List tl, tl1;
  printf("give an equation: ");
  ar = readInput();
  while (ar[0] != '!') {
    tl = tokenList(ar);
    //printf("the token list is ");
    printList(tl);
    tl1 = tl;
    if ( acceptEquation(&tl1, &deg) && tl1 == NULL ) {
      printf("this is an equation");
      printf("%d\n", deg);
      //varDeg(&tl2);
    } else {
      printf("this is not an equation\n");
    }
    free(ar);
    freeTokenList(tl);
    printf("\ngive an equation: ");
    ar = readInput();
  }
  free(ar);
  printf("good bye\n");
}


